### PR TITLE
Various code corrections

### PR DESCRIPTION
**Pull request by mruwnik**
I went throught your code and tidied it up a bit. There is still a lot that could be done, but for now that is enough. That being said, I'm impressed at what you created considering that you've been teaching yourself how to program. Especially when I think of what my early programs looked like. 
   Python is very sensitive to formating, therfore the usual way to write code is to use 4 spaces for indention. It appears that you were using tabs ('\t'), which is ok according to the python specification, but frowned upon in actual use. Therefore I took the liberty of changing tab to spaces in some files.
  You had the images hard coded into your source code, which is generally a bad idea, as I have a totally different file system. Also I didn't have the actual pictures, so I just added a couple of random ones so that the program would start.
   If you want I can do some more - there is a lot of repetition in  the Guy.py file, so that could probably simplified somewhat. If you have any questions, then don't hesitate to ask and I'll answer as soon as I can

### CODE REVIEW

**Comment by Kolodzinski** [comment]
Thank You for Your advices and corrections. This help and positive support
are definitely motivating me with further learning.
If Your interested Im sending You screens showing how the game looks with
my graphics and folder with actual graphics.
Thank You again.

2016-03-17 0:46 GMT+01:00 mruwnik <notifications@github.com>:

**Comment by mruwnik** [comment]
If you think my change are worthwhile, you can merge them into your branch and simply update the images folder with the correct pictures. It would be best to use git to do so. 
  The easiest way to start using it is to open a terminal and go to wherever you want the code to be. Then you simply execute `git clone https://github.com/Kolodzinski/Wipierman.git` which will download all the files and set the project up in a folder called `Wiperman`. It's simplest to do this somewhere else than the folder where you original code is because there will probably be name conflicts. Once you have the folder, go into it and execute `git pull`. This causes git to download all the newest changes from github. Then you can change files, add pictures, etc. Once you have all the changes you want, you execute `git add <the names of the files you want to upload>`. This marks all those files as ones you want to send to github. When you are sure of all the files, you then have to commit them. This is done by `git commit`. A commit is a selection of files that are ready to be sent. Once your commit is done, you can call `git push`, which will actually send them to github. You can find out more about it [here](https://www.git-scm.com/book/en/v1/Getting-Started). Git is worth knowing, even if you only use it for yourself. In that case you can simply think of it as a backup server that lets you retrace your steps if you mess up too much

**Comment by Kolodzinski** [comment]
Hello,
I have a question if You are still willling to help me. I just started a
new project which will be an app for enterpreneurs which wants to quick
check the ability of adding a new product to the production and if its
worth it. Itll be for small company owner who want to quick check the costs
and time consumption.
My question is how do i make a class which inherit deferent instance of
another class. There will be a class - Machine (with electricity
consumption) and which can have several instances with deferent variables.
Im tring to make class which will inherit Machine class and has its own
variable which will be the sum of every machine electricity consumption. I
foldnt find a example like this.
Thank You for Your time


2016-03-17 10:33 GMT+01:00 mruwnik <notifications@github.com>:

**Comment by mruwnik** [comment]
If I understand correctly, you can't do it with basic class inheritance. 
The problem is that each class instance is totally independent of all 
other class instances. Each instance inherits the parent class's 
methods, but not it's state, while the parent class has no idea of how 
many instances there are.
    That being said, there are ways of getting around it. The first, 
most common way it to use a factory class or function. That is simply 
something that you can call to get a new instance of a different class. 
The factory class can then count how many times it has created a new 
instance, e.g.:

class factory(object):
     machines_count = 0

     def new_machine():
         machines_count += 1
         return Machine()

     def delete_machine():
         machines_count -= 1

Your use case is a bit different, as it's not the amount of instances 
you are interested in, but the values of their properties. That can be 
fixed by changing it to `machines_electricity += machine.electricity`. A 
more pythonic way is to use metaclasses rather than a factory (factories 
are more often found in Java).
   That approach might work, but only if the consumption never changes. 
If the values can change, then the only way to know the sum is to loop 
over all instances and count the amount. Doing so requires knowing how 
many instances there are. Which can be problematic. The simplest way is 
to keep all instances in a list somewhere and just use it. But that you 
already know. If you want to use classes for it, then you can simply 
keep the list in the parent class and define a method (or even better - 
a property) that will do the counting. This could be something like the 
following:


class BaseMachine(object):
      instances = []

     def __init__(self, *args, **kwargs):
         self.instances.append(self)

     def __del__(self):
         """Make sure to remove all objects that no longer exist."""
         self.instances.remove(self)  # I think this should work, but 
I'm not sure

     @property
     def total_energy_use(self):
         # this way is more explicit and how it would look in Java
         total_use = 0
         for machine in self.instances:
             total_use += machine.electricity

         total_use = sum([machine.electricity for machine in 
self.instances])  # this way is more pythonic

         return total_use


class Machine(BaseMachine):
     electricity = 0

     def __init__(self, electricity):
         super(BaseMachine, self).__init__()  # make sure to call the 
parent's constructor
         self.electricity = electricity


Once again, the above could be made nicer using metaclasses (as this is 
what they are ideal for), but that is a complicated topic (but certainly 
worth knowing). The problem with this approach is that it will be harder 
to remove machines. Objects are removed once there are no references to 
them. For example:

def bla():
     m = SomeClass()
     return 1

bla()

would create a SomeClass instance, but only in the function. Once the 
function exits, the instance will be destroyed because there are no more 
references to it outside the function. But with the above implementation 
of BaseMachine, there will always be a reference to every instance 
created, as it will be in BaseMachine.instances. Of course you can 
remove them manually, but that is simply something you would have to 
remember. A better way would be to use a so called 'weak reference'. 
This is a reference that the garbage collector knows it can ignore. An 
example of how to use it in the context of your problem can be found at 
http://stackoverflow.com/questions/328851/printing-all-instances-of-a-class

**Pull request merged**
